Refactor and add -s option

diff --git a/pbssc b/pbssc
--- a/pbssc
+++ b/pbssc
@@ -2,55 +2,62 @@
 set -e
 
 timestamp=$(date +%Y%m%d%H%M%S)
-filename="ss-$timestamp".png
+filename="$timestamp".png
 
-# check args count
-if [ $# -gt 2 ] ; then
-  echo 'Too many args! Please run [-h] option.' >&2
-  exit 1
-fi
+# check command exists
+check_exist_command_adb() {
+  if ! command -v adb &> /dev/null; then
+    echo "adb command not found!" >&2
+    exit 1
+  fi
+}
 
-# check filename
-if [ $# = 2 ]; then
-  filename=$2
-fi
-
-# check image path
-if [ -z $PBSSC_IMAGE_PATH ]; then
-  echo 'Please set the "PBSSC_IMAGE_PATH" environment variable and try again.' >&2
-  exit 1
-fi
+# check command exists
+check_exist_command_idevicescreenshot() {
+  if ! command -v idevicescreenshot &> /dev/null; then
+    echo "idevicescreenshot command not found!" >&2
+    exit 1
+  fi
+}
 
 # capture from android device
 capture_android() {
   device_id=$(adb devices | sed '1d' | awk '{ print $1 }')
-  if [ -z "$device_id" ]; then
+  if [[ -z $device_id ]]; then
     echo "Connected android device not found!" >&2
     exit 1
   fi
-  adb exec-out screencap -p > "$PBSSC_IMAGE_PATH/$filename"
+  if [[ -z $custom_filename ]]; then
+    filepath="$PBSSC_IMAGE_PATH/android-$filename"
+  else
+    filepath="$PBSSC_IMAGE_PATH/$custom_filename"
+  fi
+  adb exec-out screencap -p > "$filepath"
 }
 
 # capture from ios device
 capture_ios() {
   device_id=$(idevice_id | awk '{ print $1 }')
-  if [ -z "$device_id" ]; then
+  if [[ -z $device_id ]]; then
     echo "Connected ios device not found!" >&2
     exit 1
   fi
-  idevicescreenshot "$PBSSC_IMAGE_PATH/$filename"
+  if [[ -z $custom_filename ]]; then
+    filepath="$PBSSC_IMAGE_PATH/ios-$filename"
+  else
+    filepath="$PBSSC_IMAGE_PATH/$custom_filename"
+  fi
+  idevicescreenshot "$filepath"
 }
 
 # image set to clipboard
 copy_to_clipboard () {
-  clipboard_file="$PBSSC_IMAGE_PATH/$filename"
-  $(
    osascript -e "
    on run
-     set the clipboard to POSIX file \"$clipboard_file\"
+     set the clipboard to POSIX file \"$filepath\"
    end
-  ")
-  echo "Set image to clipboard from $PBSSC_IMAGE_PATH/$filename"
+  "
+  echo "Set image to clipboard from $filepath"
 }
 
 help_text() {
@@ -58,8 +65,9 @@ help_text() {
 Usage: pbssc [OPTIONS] [FILE]
 
 options:
-  -a   set capture and clipboard from connected android device
-  -i   set capture and clipboard from connected ios device
+  -a   save capture and set clipboard from connected android device
+  -i   save capture and set clipboard from connected ios device
+  -s   save capture from connected devices
 
 file:
   Supported PNG format.
@@ -70,30 +78,51 @@ EOS
 }
 
 # check option
-while getopts hai OPT
+while getopts aish OPT
 do
   case $OPT in
-    a)
-      if ! command -v adb &> /dev/null; then
-        echo "adb command not found!" >&2
-        exit 1
-      fi
-      capture_android
-      copy_to_clipboard
-      ;;
-    i)
-      if ! command -v idevicescreenshot &> /dev/null; then
-        echo "idevicescreenshot command not found!" >&2
-        exit 1
-      fi
-      capture_ios
-      copy_to_clipboard
-      ;;
-    h) help_text;;
+    a) android_flag=true;;
+    i) ios_flag=true;;
+    s) save_flag=true;;
+    h) help_flag=true;;
     *) echo "'-$OPTARG' is not support.";;
   esac
 done
 
-if (( $OPTIND == 1 )); then
-   echo "Please set the options [-i] or [-a]."
+# check image path
+if [[ -z $PBSSC_IMAGE_PATH ]]; then
+  echo 'Please set the "PBSSC_IMAGE_PATH" environment variable and try again.' >&2
+  exit 1
+fi
+
+# check args count
+if [[ $# -gt 2 ]] ; then
+  echo 'Too many args! Please run [-h] option.' >&2
+  exit 1
+fi
+
+if [[ $# = 2 ]]; then
+  custom_filename=$2
+fi
+
+if [[ -n $help_flag ]]; then
+  help_text
+elif [[ -n $save_flag ]]; then
+  unset custom_filename
+  check_exist_command_idevicescreenshot
+  capture_ios
+  check_exist_command_adb
+  capture_android
+elif [[ -n $android_flag ]]; then
+  check_exist_command_adb
+  capture_android
+  copy_to_clipboard
+elif [[ -n $ios_flag ]]; then
+  check_exist_command_idevicescreenshot
+  capture_ios
+  copy_to_clipboard
+fi
+
+if (( OPTIND == 1 )); then
+ echo "Please set the options."
 fi
